### ISSUE TITLE
The inputs in RangeSliderWithInputs do not get updated.

### ISSUE THREAD

**Issue by jurajpiar** [rsksmart/rif-ui#10]
Changes to edge values for the RangeSliderWithInputs component do not trigger the change of the input fields. It seems that the min max values are not actually being used to set the input component values. I suggest revising the RangeSliderWithInputs component.

<img width="877" alt="Screenshot 2020-05-04 at 11 20 55" src="https://user-images.githubusercontent.com/36888576/80956536-54f5f600-8df9-11ea-8b9d-33fccc44773d.png">

**Comment by farinalvaro** [comment]
Solved in #22
